### ISSUE TITLE
regression: enum variant named None fails to compile in 0.4.15

### ISSUE THREAD

**Issue by ctm** [rust-lang/log#494]
I have written some poker software where it makes sense (at least to me!) to have a `None` variant. When I upgraded to log 0.4.15, my code stopped compiling. Here's a short illustration:
```
#[derive(Debug)]
pub enum Limit {
    None,
}

pub struct M {
    limit: Limit,
}

impl M {
    fn bring_in_based_min_raise(&self) {
        use Limit::*;
        log::warn!("self.limit should not be: {:?}", self.limit);
    }
}

fn main() {
    println!("Hello, world!");
}
```
```
error[E0308]: mismatched types
  --> src/main.rs:13:9
   |
13 |         log::warn!("self.limit should not be: {:?}", self.limit);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `Option`, found enum `Limit`
   |
   = note: expected enum `Option<&[(&str, &str)]>`
              found enum `Limit`
```
I've [temporarily pinned to log 0.4.14](https://github.com/ctm/mb2-doc/issues/933), which works fine.

**Comment by sfackler** [comment]
It looks like this `None` (and the `Some` above it) needs to be fully qualified: https://github.com/rust-lang/log/blob/master/src/macros.rs#L53

**Comment by Thomasdezeeuw** [comment]
@sfackler can you make a pr or want me to do it?

**Comment by sfackler** [comment]
I can make one later today, but go for it if you have the time earlier.

**Comment by Thomasdezeeuw** [comment]
#495 should fix this.

**Comment by ctm** [comment]
Thanks! I've verified locally that it does indeed fix the problem (just going through the motions for something so trivial).
